
import java.io.*;
import java.net.MalformedURLException;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    Statement statement;
    Connection connection;
    
    public void createDataBase()
    {
        try
	{
            //建表
            Class.forName("com.mysql.jdbc.Driver");
            String dbURL = "jdbc:mysql://localhost:3306/MYDB?user=root&password=zhuxin1996";
            connection = DriverManager.getConnection(dbURL);
            statement = connection.createStatement();
            //账户表
            statement.executeUpdate("CREATE DATABASE IF NOT EXISTS ");
            connection.close();
            statement.close();
            dbURL="jdbc:mysql://localhost:3306/ATM?useUnicode=true&characterEncoding=utf-8";
            connection=DriverManager.getConnection(dbURL, "root", "zhuxin1996");
            statement=connection.createStatement();
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS users"
                + "(uname varchar(12), pwd varchar(12), isLogin int ,date Date,"
                + "PRIMARY KEY(uname))");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS checking_accounts"
                + "(uname varchar(12), balance Double, PRIMARY KEY(uname))");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS saving_accounts"
                + "(ID int AUTO_INCREMENT, uname varchar(12), type int, balance Double, date Date,"
                + "PRIMARY KEY(ID),"
                + "FOREIGN KEY(uname) REFERENCES users(uname))");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS records"
                + "(date Date, uname varchar(12), type int, money Double, extra int)");
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS loan"
                + "(uname varchar(12), money Double, balance Double, date Date, PRIMARY KEY(uname))");
	}
	catch (ClassNotFoundException e) { System.out.println("无法找到驱动类");}
	catch (SQLException e) {e.printStackTrace();}
	finally 
	{
            try 
            {
		statement.close();
		connection.close();
            } 
            catch (Exception e) { e.printStackTrace();}
	}
    }
    
    private ArrayList<JButton> buttons=new ArrayList<JButton>();
    public MainWindow() {
        initComponents();
        buttons.add(Mon12S);buttons.add(Mon12D);buttons.add(Mon34S);buttons.add(Mon34D);
        buttons.add(Mon67S);buttons.add(Mon67D);buttons.add(Mon89S);buttons.add(Mon89D);
        buttons.add(Tues12S);buttons.add(Tues12D);buttons.add(Tues34S);buttons.add(Tues34D);
        buttons.add(Tues67S);buttons.add(Tues67D);buttons.add(Tues89S);buttons.add(Tues89D);
        buttons.add(Wed12S);buttons.add(Wed12D);buttons.add(Wed34S);buttons.add(Wed34D);
        buttons.add(Wed67S);buttons.add(Wed67D);buttons.add(Wed89S);buttons.add(Wed89D);
        buttons.add(Thur12S);buttons.add(Thur12D);buttons.add(Thur34S);buttons.add(Thur34D);
        buttons.add(Thur67S);buttons.add(Thur67D);buttons.add(Thur89S);buttons.add(Thur89D);
        buttons.add(Fri12S);buttons.add(Fri12D);buttons.add(Fri34S);buttons.add(Fri34D);
        buttons.add(Fri67S);buttons.add(Fri67D);buttons.add(Fri89S);buttons.add(Fri89D);
        //load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        now = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Mon12S = new javax.swing.JButton();
        Tues12S = new javax.swing.JButton();
        Wed12S = new javax.swing.JButton();
        Thur12S = new javax.swing.JButton();
        Fri12S = new javax.swing.JButton();
        Mon12D = new javax.swing.JButton();
        Tues12D = new javax.swing.JButton();
        Wed12D = new javax.swing.JButton();
        Thur12D = new javax.swing.JButton();
        Fri12D = new javax.swing.JButton();
        Mon34S = new javax.swing.JButton();
        Tues34S = new javax.swing.JButton();
        Wed34S = new javax.swing.JButton();
        Thur34S = new javax.swing.JButton();
        Fri34S = new javax.swing.JButton();
        Mon34D = new javax.swing.JButton();
        Tues34D = new javax.swing.JButton();
        Wed34D = new javax.swing.JButton();
        Thur34D = new javax.swing.JButton();
        Fri34D = new javax.swing.JButton();
        Mon67S = new javax.swing.JButton();
        Tues67S = new javax.swing.JButton();
        Wed67S = new javax.swing.JButton();
        Thur67S = new javax.swing.JButton();
        Fri67S = new javax.swing.JButton();
        Mon67D = new javax.swing.JButton();
        Tues67D = new javax.swing.JButton();
        Wed67D = new javax.swing.JButton();
        Thur67D = new javax.swing.JButton();
        Fri67D = new javax.swing.JButton();
        Mon89S = new javax.swing.JButton();
        Tues89S = new javax.swing.JButton();
        Wed89S = new javax.swing.JButton();
        Thur89S = new javax.swing.JButton();
        Fri89S = new javax.swing.JButton();
        Mon89D = new javax.swing.JButton();
        Tues89D = new javax.swing.JButton();
        Wed89D = new javax.swing.JButton();
        Thur89D = new javax.swing.JButton();
        Fri89D = new javax.swing.JButton();
        MonLabel = new javax.swing.JLabel();
        TuesLabel = new javax.swing.JLabel();
        WedLabel = new javax.swing.JLabel();
        ThurLabel = new javax.swing.JLabel();
        FriLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("学期（如16-17-3）");

        jTextField1.setText("17-18-3");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("学号：");

        confirmButton.setText("确定");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("71115134");
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(confirmButton))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(now, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(now, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton))
        );

        Mon12S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon12S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon12SActionPerformed(evt);
            }
        });

        Tues12S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues12S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues12SActionPerformed(evt);
            }
        });

        Wed12S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed12S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed12SActionPerformed(evt);
            }
        });

        Thur12S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur12S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur12SActionPerformed(evt);
            }
        });

        Fri12S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri12S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri12SActionPerformed(evt);
            }
        });

        Mon12D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon12DActionPerformed(evt);
            }
        });

        Tues12D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues12DActionPerformed(evt);
            }
        });

        Wed12D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed12DActionPerformed(evt);
            }
        });

        Thur12D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur12DActionPerformed(evt);
            }
        });

        Fri12D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri12D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri12DActionPerformed(evt);
            }
        });

        Mon34S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon34S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon34SActionPerformed(evt);
            }
        });

        Tues34S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues34S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues34SActionPerformed(evt);
            }
        });

        Wed34S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed34S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed34SActionPerformed(evt);
            }
        });

        Thur34S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur34S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur34SActionPerformed(evt);
            }
        });

        Fri34S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri34S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri34SActionPerformed(evt);
            }
        });

        Mon34D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon34D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon34DActionPerformed(evt);
            }
        });

        Tues34D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues34D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues34DActionPerformed(evt);
            }
        });

        Wed34D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed34D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed34DActionPerformed(evt);
            }
        });

        Thur34D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur34D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur34DActionPerformed(evt);
            }
        });

        Fri34D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri34D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri34DActionPerformed(evt);
            }
        });

        Mon67S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon67S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon67SActionPerformed(evt);
            }
        });

        Tues67S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues67S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues67SActionPerformed(evt);
            }
        });

        Wed67S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed67S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed67SActionPerformed(evt);
            }
        });

        Thur67S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur67S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur67SActionPerformed(evt);
            }
        });

        Fri67S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri67S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri67SActionPerformed(evt);
            }
        });

        Mon67D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon67D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon67DActionPerformed(evt);
            }
        });

        Tues67D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues67D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues67DActionPerformed(evt);
            }
        });

        Wed67D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed67D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed67DActionPerformed(evt);
            }
        });

        Thur67D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur67D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur67DActionPerformed(evt);
            }
        });

        Fri67D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri67D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri67DActionPerformed(evt);
            }
        });

        Mon89S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon89S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon89SActionPerformed(evt);
            }
        });

        Tues89S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues89S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues89SActionPerformed(evt);
            }
        });

        Wed89S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed89S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed89SActionPerformed(evt);
            }
        });

        Thur89S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur89S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur89SActionPerformed(evt);
            }
        });

        Fri89S.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri89S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri89SActionPerformed(evt);
            }
        });

        Mon89D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Mon89D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mon89DActionPerformed(evt);
            }
        });

        Tues89D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Tues89D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tues89DActionPerformed(evt);
            }
        });

        Wed89D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Wed89D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wed89DActionPerformed(evt);
            }
        });

        Thur89D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Thur89D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thur89DActionPerformed(evt);
            }
        });

        Fri89D.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        Fri89D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fri89DActionPerformed(evt);
            }
        });

        MonLabel.setText("周一");

        TuesLabel.setText("周二");

        WedLabel.setText("周三");

        ThurLabel.setText("周四");

        FriLabel.setText("周五");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon12S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues12S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed12S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur12S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri12S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon12D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues12D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed12D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur12D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri12D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon34S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues34S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed34S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur34S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri34S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon34D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues34D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed34D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur34D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri34D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon67S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues67S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed67S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur67S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri67S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon67D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues67D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed67D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur67D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri67D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon89S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues89S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed89S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur89S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri89S, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mon89D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tues89D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wed89D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thur89D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fri89D, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(MonLabel)
                        .addGap(43, 43, 43)
                        .addComponent(TuesLabel)
                        .addGap(43, 43, 43)
                        .addComponent(WedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ThurLabel)
                        .addGap(46, 46, 46)
                        .addComponent(FriLabel)
                        .addGap(28, 28, 28))))
            .addComponent(jSeparator4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonLabel)
                    .addComponent(TuesLabel)
                    .addComponent(WedLabel)
                    .addComponent(ThurLabel)
                    .addComponent(FriLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon12S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues12S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri12S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed12S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur12S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon12D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues12D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri12D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed12D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur12D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon34S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues34S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri34S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed34S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur34S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon34D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues34D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri34D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed34D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur34D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon67S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues67S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri67S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed67S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur67S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon67D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues67D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri67D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed67D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur67D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon89S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues89S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri89S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed89S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur89S, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mon89D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tues89D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fri89D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wed89D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thur89D, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //值班时间映射到课表时间
    private int f(int x)
    {
        switch(x)
        {
            case 0:return 0;
            case 1:return 2;
            case 2:return 5;
            case 3:return 7;
            default: return -1;
        }
    }
    
    private int min(int x,int y)
    {
        return (x>y)?y:x;
    }
    
    private int find(Person x,int y)
    {
        for (int i=0;i<5;i++)
            for (int j=0;j<4;j++)
            {
                if (x.getClasses()[i][f(j)]==null && x.getClasses()[i][f(j)+1]==null && state[i*4+j]==0)
                {
                    state[i*4+j]=1;//标记为搜索过
                    if (finalAttendance[i][j][y]==null      //未被匹配过
                    || find(finalAttendance[i][j][y],y)==1 )  //能找到一条增广路
                    {
                        finalAttendance[i][j][y]=x;         //匹配i,x
                        return 1;                           //能找到新的匹配
                    }
                }
            }
        return 0;
    }
    
    int state[]=new int[20];  //标记一次循环中是否搜索过
    
    private void BipartiteMatch()
    {
        int ans=0;
        for (int i=0;i<persons.size();i++)
        {
            for (int j=0;j<20;j++) state[j]=0;
            if (find(persons.get(i),0)==1) ans++;
        }
        //剩余的人排双周
        HashMap<Person,Integer> isAttendance=new HashMap<Person,Integer>();
        for (int i=0;i<persons.size();i++) isAttendance.put(persons.get(i), 0);
        for (int i=0;i<5;i++)
            for (int j=0;j<4;j++)
                isAttendance.put(finalAttendance[i][j][0], 1);
        for (int i=0;i<persons.size();i++)
            if (isAttendance.get(persons.get(i))==0)
            {
                for (int j=0;j<20;j++) state[j]=0;
                if (find(persons.get(i),1)==1) ans++;
            }
    }
    
    private String[] haveRested={"213171423",//彭维锋
                             "213171288",//黄胤宁
                             "213173110",//邢友君
                             "213171959",//巫明蓉
                             "213170779",//李逸文
                             "213170394",//陈睿毅
                             "213172490",//祝铭阳
                             "213173185",//薛明扬
                             "213170848",//苏之舟
                             "213172393",//张慕
                             "213173454",//喻沛文
                             "213172728",//马宇翔
                             "213173544",//朱恺琪
                             "213172131",//贺柳
                             "213171849",//王晓雪
                             "213170261",//高喆
        };
    
    private void arrangement()
    {
        for (Iterator it=buttons.iterator();it.hasNext();)
        {
            JButton btn=(JButton)it.next();
            btn.setLabel("");
        }
        int countRest=0,minCountRest=16;
        Person[][][] finalFinalAttendance=new Person[5][4][2];
        for (int i=0;i<5;i++)
            for (int j=0;j<4;j++)
                for (int k=0;k<2;k++)
                   finalFinalAttendance[i][j][k]=null;
        Random rand = new Random();
        for (int t=0;t<100000;t++)
        {
            int tt=rand.nextInt(20)+1;
            for (int ttt=0;ttt<tt;ttt++)
            {
                int x=rand.nextInt(persons.size()),y=rand.nextInt(persons.size());
                Person temp=persons.get(x);
                persons.set(x, persons.get(y));
                persons.set(y, temp);
            }
            maxnum=0;
            for (int i=0;i<5;i++)
                for (int j=0;j<4;j++)
                    for (int k=0;k<2;k++)
                    {
                        attendance[i][j][k]=null;
                        finalAttendance[i][j][k]=null;
                    }
            BipartiteMatch();
            for (int i=0;i<5;i++)
                for (int j=0;j<4;j++)
                    if (finalAttendance[i][j][1]!=null)
                    {
                        if (checkRested(finalAttendance[i][j][0])) countRest++;
                        if (checkRested(finalAttendance[i][j][1])) countRest++;
                    }
            if (countRest<minCountRest)
            {
                minCountRest=countRest;
                for (int i=0;i<5;i++)
                    for (int j=0;j<4;j++)
                        for (int k=0;k<2;k++)
                            finalFinalAttendance[i][j][k]=finalAttendance[i][j][k];
            }
        }
        System.out.println(minCountRest);
        for (int i=0;i<5;i++)
            for (int j=0;j<4;j++) finalAttendance[i][j]=finalFinalAttendance[i][j].clone();
        save();
        display();
    }
    
    private Boolean checkRested(Person p)
    {
        for (int i=0;i<16;i++)
            if (p.getCardNumber().equals(haveRested[i]))
            {
                //System.out.println(p.getName());
                return true;
            }
        return false;
    }
    
    private void display()
    {
        for (int i=0;i<5;i++)
            for (int j=0;j<4;j++)
                for (int k=0;k<2;k++)
                {
                    Person p=finalAttendance[i][j][k];
                    if (p!=null) buttons.get(i*8+j*2+k).setLabel(p.getName());
                }
    }
    
    private void save()
    {
        try 
	{
            FileOutputStream fos=new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(persons);
            oos.flush();
            oos.close();
        } 
	catch (IOException e) 
	{
            e.printStackTrace();
        }
    }
    
    private void load()
    {
        try
	{
            FileInputStream file_in = new FileInputStream(f);
            ObjectInputStream ob_in = new ObjectInputStream(file_in);
            if (file_in.available()>0)
            {
                persons=(ArrayList<Person>)ob_in.readObject();
                Person.setNumber(persons.size());
                arrangement();
            }
            ob_in.close();
	}
	catch (IOException e) 
	{
            e.printStackTrace();
        } 
	catch (Exception e) 
	{
            e.printStackTrace();
	}
    }
    
    private void setBusy(int x)
    {
        int i=x/8;
        int j=(x-i*8)/2;
        int k=x-i*8-j*2;
        int tj;
        switch(j) 
        {
            case 0:tj=0;break;
            case 1:tj=2;break;
            case 2:tj=5;break;
            case 3:tj=7;break;
            default:tj=0;break;
        }
        finalAttendance[i][j][k].setBusy(i,tj);
        arrangement();
    }
    
    private File f=new File("save.dat");
    private int maxnum;
    private Person[][][] attendance=new Person[5][4][2];
    private Person[][][] finalAttendance=new Person[5][4][2];   //最终结果
    private ArrayList<Person> persons=new ArrayList<Person>();  //人员名单
    
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        persons.clear();
        this.now.setText("");
        Person.setNumber(0);
        String year=this.jTextField1.getText();
        String ids=this.jTextArea1.getText();
        String id=null;
        int beginInx=0;
        int endInx=ids.indexOf("\n");
        try
        {
            for (;endInx!=-1;beginInx=endInx+1,endInx=ids.indexOf("\n",beginInx))
            {
                id=ids.substring(beginInx,endInx);
                if (id==null || id.equals("")) continue;
                this.now.setText(id);
                Person p=new Person(id,year);
                persons.add(p);
            }
            id=ids.substring(beginInx);
            if (id!=null && !id.equals(""))
            {
                this.now.setText(id);
                Person p=new Person(id,year);
                persons.add(p);
            }
            this.now.setText("over");
            //arrangement();
            for (int i=0;i<Person.number;i++)
            {  
                boolean flag=true;
                for (int j=7;j<11;j++)
                    if (persons.get(i).classes[3][j]!=null)
                    {
                        flag=false;
                        break;
                    }
                if (flag) System.out.println(persons.get(i).getName());
            }
            //for (int i=0;i<Person.number;i++)
                //System.out.println(persons.get(i).getCardNumber());
            //System.out.println("-------------------------");
        }
        catch(UnknownHostException e)
        {
            JOptionPane.showMessageDialog(this,id+"获取课表失败");
            e.printStackTrace();
        }
        catch(MalformedURLException e)
        {
            JOptionPane.showMessageDialog(this,id+"获取课表失败");
            e.printStackTrace();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,id+"获取课表失败");
            e.printStackTrace();
        }
        catch(Exception e)
        {
            if (e.getMessage().equals("连接出错")) JOptionPane.showMessageDialog(this,id+"获取课表失败");
            e.printStackTrace();
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void Tues12SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues12SActionPerformed
        // TODO add your handling code here:
        setBusy(8);
    }//GEN-LAST:event_Tues12SActionPerformed

    private void Mon12SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon12SActionPerformed
        // TODO add your handling code here:
        setBusy(0);
    }//GEN-LAST:event_Mon12SActionPerformed

    private void Wed12SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed12SActionPerformed
        // TODO add your handling code here:
        setBusy(16);
    }//GEN-LAST:event_Wed12SActionPerformed

    private void Fri12SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri12SActionPerformed
        // TODO add your handling code here:
        setBusy(32);
    }//GEN-LAST:event_Fri12SActionPerformed

    private void Thur12SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur12SActionPerformed
        // TODO add your handling code here:
        setBusy(24);
    }//GEN-LAST:event_Thur12SActionPerformed

    private void Tues12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues12DActionPerformed
        // TODO add your handling code here:
        setBusy(9);
    }//GEN-LAST:event_Tues12DActionPerformed

    private void Mon12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon12DActionPerformed
        // TODO add your handling code here:
        setBusy(1);
    }//GEN-LAST:event_Mon12DActionPerformed

    private void Wed12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed12DActionPerformed
        // TODO add your handling code here:
        setBusy(17);
    }//GEN-LAST:event_Wed12DActionPerformed

    private void Fri12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri12DActionPerformed
        // TODO add your handling code here:
        setBusy(33);
    }//GEN-LAST:event_Fri12DActionPerformed

    private void Thur12DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur12DActionPerformed
        // TODO add your handling code here:
        setBusy(25);
    }//GEN-LAST:event_Thur12DActionPerformed

    private void Mon34SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon34SActionPerformed
        // TODO add your handling code here:
        setBusy(2);
    }//GEN-LAST:event_Mon34SActionPerformed

    private void Tues34SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues34SActionPerformed
        // TODO add your handling code here:
        setBusy(10);
    }//GEN-LAST:event_Tues34SActionPerformed

    private void Wed34SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed34SActionPerformed
        // TODO add your handling code here:
        setBusy(18);
    }//GEN-LAST:event_Wed34SActionPerformed

    private void Thur34SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur34SActionPerformed
        // TODO add your handling code here:
        setBusy(26);
    }//GEN-LAST:event_Thur34SActionPerformed

    private void Fri34SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri34SActionPerformed
        // TODO add your handling code here:
        setBusy(34);
    }//GEN-LAST:event_Fri34SActionPerformed

    private void Fri34DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri34DActionPerformed
        // TODO add your handling code here:
        setBusy(35);
    }//GEN-LAST:event_Fri34DActionPerformed

    private void Thur34DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur34DActionPerformed
        // TODO add your handling code here:
        setBusy(27);
    }//GEN-LAST:event_Thur34DActionPerformed

    private void Wed34DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed34DActionPerformed
        // TODO add your handling code here:
        setBusy(19);
    }//GEN-LAST:event_Wed34DActionPerformed

    private void Tues34DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues34DActionPerformed
        // TODO add your handling code here:
        setBusy(11);
    }//GEN-LAST:event_Tues34DActionPerformed

    private void Mon34DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon34DActionPerformed
        // TODO add your handling code here:
        setBusy(3);
    }//GEN-LAST:event_Mon34DActionPerformed

    private void Mon67SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon67SActionPerformed
        // TODO add your handling code here:
        setBusy(4);
    }//GEN-LAST:event_Mon67SActionPerformed

    private void Tues67SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues67SActionPerformed
        // TODO add your handling code here:
        setBusy(12);
    }//GEN-LAST:event_Tues67SActionPerformed

    private void Wed67SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed67SActionPerformed
        // TODO add your handling code here:
        setBusy(20);
    }//GEN-LAST:event_Wed67SActionPerformed

    private void Thur67SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur67SActionPerformed
        // TODO add your handling code here:
        setBusy(28);
    }//GEN-LAST:event_Thur67SActionPerformed

    private void Fri67SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri67SActionPerformed
        // TODO add your handling code here:
        setBusy(36);
    }//GEN-LAST:event_Fri67SActionPerformed

    private void Fri67DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri67DActionPerformed
        // TODO add your handling code here:
        setBusy(37);
    }//GEN-LAST:event_Fri67DActionPerformed

    private void Thur67DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur67DActionPerformed
        // TODO add your handling code here:
        setBusy(29);
    }//GEN-LAST:event_Thur67DActionPerformed

    private void Wed67DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed67DActionPerformed
        // TODO add your handling code here:
        setBusy(21);
    }//GEN-LAST:event_Wed67DActionPerformed

    private void Tues67DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues67DActionPerformed
        // TODO add your handling code here:
        setBusy(13);
    }//GEN-LAST:event_Tues67DActionPerformed

    private void Mon67DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon67DActionPerformed
        // TODO add your handling code here:
        setBusy(5);
    }//GEN-LAST:event_Mon67DActionPerformed

    private void Mon89SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon89SActionPerformed
        // TODO add your handling code here:
        setBusy(6);
    }//GEN-LAST:event_Mon89SActionPerformed

    private void Tues89SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues89SActionPerformed
        // TODO add your handling code here:
        setBusy(14);
    }//GEN-LAST:event_Tues89SActionPerformed

    private void Wed89SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed89SActionPerformed
        // TODO add your handling code here:
        setBusy(22);
    }//GEN-LAST:event_Wed89SActionPerformed

    private void Thur89SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur89SActionPerformed
        // TODO add your handling code here:
        setBusy(30);
    }//GEN-LAST:event_Thur89SActionPerformed

    private void Fri89SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri89SActionPerformed
        // TODO add your handling code here:
        setBusy(38);
    }//GEN-LAST:event_Fri89SActionPerformed

    private void Fri89DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fri89DActionPerformed
        // TODO add your handling code here:
        setBusy(39);
    }//GEN-LAST:event_Fri89DActionPerformed

    private void Thur89DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thur89DActionPerformed
        // TODO add your handling code here:
        setBusy(31);
    }//GEN-LAST:event_Thur89DActionPerformed

    private void Wed89DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wed89DActionPerformed
        // TODO add your handling code here:
        setBusy(23);
    }//GEN-LAST:event_Wed89DActionPerformed

    private void Tues89DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tues89DActionPerformed
        // TODO add your handling code here:
        setBusy(15);
    }//GEN-LAST:event_Tues89DActionPerformed

    private void Mon89DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mon89DActionPerformed
        // TODO add your handling code here:
        setBusy(7);
    }//GEN-LAST:event_Mon89DActionPerformed

    private void jTextArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusGained
        // TODO add your handling code here:
        this.now.setText(null);
    }//GEN-LAST:event_jTextArea1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fri12D;
    private javax.swing.JButton Fri12S;
    private javax.swing.JButton Fri34D;
    private javax.swing.JButton Fri34S;
    private javax.swing.JButton Fri67D;
    private javax.swing.JButton Fri67S;
    private javax.swing.JButton Fri89D;
    private javax.swing.JButton Fri89S;
    private javax.swing.JLabel FriLabel;
    private javax.swing.JButton Mon12D;
    private javax.swing.JButton Mon12S;
    private javax.swing.JButton Mon34D;
    private javax.swing.JButton Mon34S;
    private javax.swing.JButton Mon67D;
    private javax.swing.JButton Mon67S;
    private javax.swing.JButton Mon89D;
    private javax.swing.JButton Mon89S;
    private javax.swing.JLabel MonLabel;
    private javax.swing.JButton Thur12D;
    private javax.swing.JButton Thur12S;
    private javax.swing.JButton Thur34D;
    private javax.swing.JButton Thur34S;
    private javax.swing.JButton Thur67D;
    private javax.swing.JButton Thur67S;
    private javax.swing.JButton Thur89D;
    private javax.swing.JButton Thur89S;
    private javax.swing.JLabel ThurLabel;
    private javax.swing.JButton Tues12D;
    private javax.swing.JButton Tues12S;
    private javax.swing.JButton Tues34D;
    private javax.swing.JButton Tues34S;
    private javax.swing.JButton Tues67D;
    private javax.swing.JButton Tues67S;
    private javax.swing.JButton Tues89D;
    private javax.swing.JButton Tues89S;
    private javax.swing.JLabel TuesLabel;
    private javax.swing.JButton Wed12D;
    private javax.swing.JButton Wed12S;
    private javax.swing.JButton Wed34D;
    private javax.swing.JButton Wed34S;
    private javax.swing.JButton Wed67D;
    private javax.swing.JButton Wed67S;
    private javax.swing.JButton Wed89D;
    private javax.swing.JButton Wed89S;
    private javax.swing.JLabel WedLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel now;
    // End of variables declaration//GEN-END:variables
}
